### ISSUE TITLE
!gtfobins allows spamming @everyone

### ISSUE THREAD

**Issue by michalani** [DarkStar7471/THM-Bot#126]
**Describe the bug**
gtfobins command Allows users to spam @everyone

**To Reproduce**
1. Go to the following tryhackme discord channel
https://discordapp.com/channels/521382216299839518/610854557299376168/730546540732481646
2. Type
!gtfobins @everyone

3. $$$
**Expected behavior**
An error message of some kind.

**Screenshots**
[showcase](https://i.imgur.com/SGleqlY.png)

**Comment by horshark** [comment]
Thank you for reporting this issue!


This should get solved when the following issue gets solved.

https://github.com/DarkStar7471/THM-Bot/issues/125
